name: Testes PHP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: primeiro passo
        run: echo "world"

      - name: segundo passo
        run: echo "hello"
